version: '3'
services:
  db:
    image: mysql
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
    container_name: phpmyadmin_local
    image: phpmyadmin/phpmyadmin
    ports:
      - ${DB_ADMIN_PORT}:80
    environment:
      PMA_HOSTS: mysql_local
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    
    